'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\Users\david.skarka\Documents\Priv\MTU\")>  _
        Public Property ArchiImportDirectory() As String
            Get
                Return CType(Me("ArchiImportDirectory"),String)
            End Get
            Set
                Me("ArchiImportDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("elements.csv")>  _
        Public Property ArchiImportFileElements() As String
            Get
                Return CType(Me("ArchiImportFileElements"),String)
            End Get
            Set
                Me("ArchiImportFileElements") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("properties.csv")>  _
        Public Property ArchiImportFileProperties() As String
            Get
                Return CType(Me("ArchiImportFileProperties"),String)
            End Get
            Set
                Me("ArchiImportFileProperties") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("relations.csv")>  _
        Public Property ArchiImportFileRelations() As String
            Get
                Return CType(Me("ArchiImportFileRelations"),String)
            End Get
            Set
                Me("ArchiImportFileRelations") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("csv")>  _
        Public Property ArchiImportFileFormat() As String
            Get
                Return CType(Me("ArchiImportFileFormat"),String)
            End Get
            Set
                Me("ArchiImportFileFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\Users\david.skarka\Documents\Priv\MTU\")>  _
        Public Property SparxEATargetRepostoryDirectory() As String
            Get
                Return CType(Me("SparxEATargetRepostoryDirectory"),String)
            End Get
            Set
                Me("SparxEATargetRepostoryDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MTU2.eap")>  _
        Public Property SparxEATargetRepostoryFile() As String
            Get
                Return CType(Me("SparxEATargetRepostoryFile"),String)
            End Get
            Set
                Me("SparxEATargetRepostoryFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eap")>  _
        Public Property SparxEATargetRepostoryFormat() As String
            Get
                Return CType(Me("SparxEATargetRepostoryFormat"),String)
            End Get
            Set
                Me("SparxEATargetRepostoryFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("importedFromArchi")>  _
        Public Property SparxEATargetRepostoryPackageArchiImported() As String
            Get
                Return CType(Me("SparxEATargetRepostoryPackageArchiImported"),String)
            End Get
            Set
                Me("SparxEATargetRepostoryPackageArchiImported") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Global")>  _
        Public Property SparxEATargetRepostoryModelArchiImported() As String
            Get
                Return CType(Me("SparxEATargetRepostoryModelArchiImported"),String)
            End Get
            Set
                Me("SparxEATargetRepostoryModelArchiImported") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T.O.O.L.B.O.X")>  _
        Public Property Author() As String
            Get
                Return CType(Me("Author"),String)
            End Get
            Set
                Me("Author") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.com.daudus.My.MySettings
            Get
                Return Global.com.daudus.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
